### ISSUE TITLE
Migration generator not working properly

### ISSUE THREAD

**Issue by YanDeLeon** [leapkit/template#1]
I am experiencing issues with the migration generator in LeapKit. It seems to not be working as expected, and I wanted to report the problem.

**Steps to Reproduce:**
- Follow installation steps from [Socket.dev](https://socket.dev/go/package/github.com/leapkit/template?section=overview&version=v1.1.0) 
- run `go run ./cmd/gen migration [name]`

**Expected Behavior:**
- Migration file is generated

**Actual Behavior:**
- Error: error creating migration file: open internal/migrations/20240122155707_name.sql: no such file or directory

**Comment by paganotoni** [comment]
This one should be fixed now. Many changes in the Leapkit template folder structure caused it.
